[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "#C8E690"
playing = "#C8E690"
playing_bg = "black"
playing_selected = "#C8E690"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#C8E690"
statusbar_bg = "#C8E690"
bar = "#C8E690"
cmdline = "light white"
cmdline_bg = "black"
