[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "cyan"
playing = "cyan"
playing_bg = "black"
playing_selected = "cyan"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "cyan"
statusbar_bg = "cyan"
bar = "cyan"
cmdline = "light white"
cmdline_bg = "black"
